version: "3.8"
services:
    react:
           build: ./react
           container_name: react
           ports:
             - "3000:3000"
           stdin_open: true
           tty: true
           depends_on:
             - mongo
             - kafka
             - zookeeper
          
    mongo:
      image: mongo
      container_name: mongo
      hostname: mongo
      ports:
        - "27017:27017"
      stdin_open: true
      environment:
        - MONGO_INITDB_DATABASE=IES
      tty: true
      volumes: 
        - ./mongo:/data/db
        - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js 
    zookeeper:
         image: wurstmeister/zookeeper
         container_name: zookeeper
         ports:
           - "2181:2181"
         depends_on:
           - mongo
    kafka:
         image: wurstmeister/kafka
         container_name: kafka
         ports:
           - "9092:9092"
         environment:
           KAFKA_ADVERTISED_HOST_NAME: localhost
           KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
         healthcheck:
           test: cd opt/kafka_*/bin/ && sleep 10 && kafka-topics.sh --create --zookeeper zookeeper:2181  --replication-factor 1 --partitions 1 --topic gameHoursTopic
           interval: 60s
           retries: 5
           start_period: 20s
           timeout: 10s
         depends_on:
           - zookeeper
           - mongo
